if(CMAKE_SIZEOF_VOID_P EQUAL 4)
  set(ARCH "32")
elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(ARCH "64")
endif()

if(
  CMAKE_BUILD_TYPE STREQUAL "Release"
  AND
  EKG_EMSCRIPTEN_BUILD_TYPE
  OR
  CMAKE_CXX_COMPILER_ID STREQUAL "GNU"
  OR
  CMAKE_CXX_COMPILER_ID STREQUAL "Clang"
)
  set(COMPILE_OPTIMIZATION_NUMBER -O3)
endif()

if(WIN32 OR VOKE_FORCE_WINDOWS)
  set(EXECUTABLE_OUTPUT_PATH "../bin/windows/${ARCH}")
  set(PLATFORM "windows-${ARCH}")
endif()